#'plot_npx_norm_qc (Generate QC plots pre and post normalization)
#'@description normalization QC plots, generate
#'             1) analyt/pre vs post scatter plot, colored by plates
#'             2) optional to select a analyt of choice plot for
#'                pre vs post npx by plates scatter plots
#'             3) optional plot to track Randox behavior pre and post normalization
#'                if randox_info is given plot the targeted value
#'@param normed_se a summarizedexperiment, normaly generated by cmb_npx_sc() after normalization
#'@param bridge_pattern regex to identify bridging samples
#'@param fields colData name from which to identify bridging samples uing the bridge_pattern
#'@param example (optional)string of a analyt name, defalult is NULL
#'@param Randox (optional) if to track Randox among plates, defalult is F
#'@param randox_info_f (optional) if to plot Randox's target value. required to generate a csv file from
#'                    the product.info sheet manually.
#'      Analyt	Randox	Target	SD
#'       IL2	Randox_1	49.81	  8.72
#'       IL2	Randox_2	191.77	33.56
#'       IL2	Randox_3	399.19	69.87
#'       IL4	Randox_1	18.8	  3.29
#'       IL4	Randox_2	67.69	  11.85
#'       IL4	Randox_3	241.12	42.2
#'       IL6	Randox_1	16.36	  2.69
#'@export
#'@md
#'
plot_npx_norm_qc <- function(normed_se, bridge_pattern= "HD Urine Pool", fields = "Assay", example = NULL,
                    Randox = F, randox_info_f = NULL){

  bridge <- normed_se[, grep(bridge_pattern, normed_se[[fields]])]

  assay_ls <- names(bridge@assays@data)
  bridge_data_ls <- lapply(assay_ls, function(x){
    bridge@assays@data[[x]] %>%
      data.frame()%>%
      set_colnames(value = bridge$f_name)%>%
      rownames_to_column(var = "Analyt") %>%
      gather(-Analyt, key = "f_name", value = "value")%>%
      mutate(Assay = x,
             f_name = gsub("^.*/", "", f_name))
  })
  bridge_data_ls <- do.call(rbind, bridge_data_ls)%>%
    mutate(f_name = gsub("\\.[0-9]+$", "", f_name))

  normed_se_ls <- lapply(assay_ls, function(x){
    normed_se@assays@data[[x]] %>%
      data.frame()%>%
      set_colnames(value = normed_se$f_name)%>%
      rownames_to_column(var = "Analyt") %>%
      gather(-Analyt, key = "f_name", value = "value")%>%
      mutate(Assay = x,
             f_name = gsub("^.*/", "", f_name))
  })
  normed_se_ls <- do.call(rbind, normed_se_ls)%>%
    mutate(f_name = gsub("\\.[0-9]+$", "", f_name))

  p1 <- bridge_data_ls %>%
    mutate(Assay = factor(Assay, levels = c("npx", "inlot_normed")))%>%
    ggplot()+
    geom_point(aes(value, Analyt, color = f_name), shape = 21, size = 4)+
    geom_point(aes(LOD, Analyt), data = data.frame(normed_se@elementMetadata))+
    labs(title = "Bridge QC Reference")+
    facet_grid( ~ Assay)+
    theme_bw()+
    theme(legend.position = "none")+
    theme(axis.text.x = element_text(angle = 60, hjust = 1))

  re <- list("all" = p1)

  if(!is.null(example)){
    p2 <- bridge_data_ls %>%
      dplyr::filter(Analyt == example)%>%
      mutate(Assay = factor(Assay, levels = c("npx", "inlot_normed")))%>%
      ggplot()+
      geom_point(aes(value, f_name, color = f_name), shape = 16, size = 6)+
      geom_vline(xintercept = normed_se@elementMetadata$LOD[normed_se@elementMetadata$Analyt == example],
                 color = "red", linetype = 2)+
      labs(title = "Example Bridge QC Reference")+
      facet_wrap( ~ Assay, nrow = 1)+
      theme_bw()+
      theme(legend.position = "none")+
      coord_flip()+
      theme(axis.text.x = element_text(angle = 60, hjust = 1))

    p3 <- normed_se_ls %>%
      dplyr::filter(Analyt == example)%>%
      mutate(Assay = factor(Assay, levels = c("npx", "inlot_normed")))%>%
      ggplot()+
      geom_jitter(aes(value, f_name, color = f_name), shape = 21, size = 6)+
      geom_vline(xintercept = normed_se@elementMetadata$LOD[normed_se@elementMetadata$Analyt == example],
                 color = "red", linetype = 2)+
      labs(title = "Example Analyt QC Reference")+
      facet_wrap( ~ Assay, nrow = 1)+
      theme_bw()+
      theme(legend.position = "none")+
      coord_flip()+
      theme(axis.text.x = element_text(angle = 60, hjust = 1))

    re[["example_bdg"]] <- p2
    re[["example_sample"]] <- p3
  }

  if(Randox){
    randox <- normed_se[, grep("randox", ignore.case = T, normed_se[[fields]])]
    assay_ls <- names(randox@assays@data)
    randox_data_ls <- lapply(assay_ls, function(x){
      randox@assays@data[[x]] %>%
        data.frame()%>%
        set_colnames(value = paste(randox$f_name, randox$Assay, sep = "--"))%>%
        rownames_to_column(var = "Analyt") %>%
        gather(-Analyt, key = "f_name", value = "value")%>%
        mutate(Assay = x,
               f_name = gsub("^.*/", "", f_name))
    })
    randox_data_ls <- do.call(rbind, randox_data_ls)%>%
      separate(col = f_name, into = c("f_name", "Randox"), sep = "--")%>%
      mutate(f_name = gsub("\\.[0-9]+$", "", f_name),
             Randox = gsub("_P[0-9]+$", "", Randox))
    randox.metric <- randox_data_ls %>%
      group_by(Analyt, Randox, Assay)%>%
      summarize(mean = mean(value, na.rm = T),
                sd = sd(value, na.rm = T))

    randox_data_ls <- randox_data_ls%>%
      left_join(randox.metric)

    randox_analyt <- c("IL2", "IL4", "IL6", "IL8", "IL10",
                       "VEGFA", "IFN.gamma", "TNF",
                       "MCP.1", "EGF")

    p4 <- lapply(randox_analyt, function(y){
      p0 <- randox_data_ls %>%
        dplyr::filter(Analyt == y)%>%
        mutate(Assay = gsub("(CIMAC_10026_|_NPX.xlsx)", "", Assay))%>%
        mutate(Assay = factor(Assay, levels = c("npx", "inlot_normed")))%>%
        ggplot()+
        geom_point(aes(f_name, value, color = Randox), shape = 21, size = 6)+
        geom_hline(yintercept = normed_se@elementMetadata$LOD[normed_se@elementMetadata$Analyt == y],
                   color = "red", linetype = 4)+
        labs(title = y)+
        facet_wrap( ~ Assay)+
        theme_bw()+
        theme(legend.position = "none")+
        theme(axis.text.x = element_text(angle = 60, hjust = 1))

      if(!is.null(randox_info_f)){
        df <- read.csv(randox_info_f)
        df <- df%>%
          dplyr::filter(Analyt == y)%>%
          mutate_if(is.numeric, log2)%>%
          mutate(upper = Target + SD,
                 under = Target - SD)%>%
          dplyr::select(Analyt, Randox, Target, upper, under)

        p0 <- p0+geom_hline(data = df, aes(yintercept = Target, color = Randox))+
          geom_hline(data = df, aes(yintercept = upper, color = Randox), linetype = 2)+
          geom_hline(data = df, aes(yintercept = under, color = Randox), linetype = 2)+
          scale_color_manual(values = c("purple", "dark green", "blue",
                                        "purple", "dark green", "blue",
                                        "purple", "dark green", "blue",
                                        "purple", "dark green", "blue"))

      }
      p0
    })
    for (i in 1:2) {
      p <- p4[(1 + 5 * (i-1)) : (5 + 5 * (i-1))]
      p <- wrap_plots(p[!sapply(p, is.null)], ncol = 5)
      r_name <- paste("randox", i, sep = "_")
      re[[r_name]] <- p
    }

  }

  return(re)
}
